name: CI Checks
run-name: Running Terraform Checks by ${{ github.actor }}

on:
 pull_request:
   branches:
     - main

jobs:
  Initial-Checks:
    runs-on: ubuntu-latest

    steps:
    - name: Getting initiator name
      run: echo "Workflow initiated by ${{ github.actor }} from branch ${{ github.ref_name }}"

  terraform-checks:
    runs-on: ubuntu-latest
    needs: Initial-Checks
    outputs:
      status: ${{ job.status }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: latest
    
    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact

  snyk-checks:
    name: Snyk Security Scans
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js (for Snyk CLI)
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Authenticate with Snyk
      env:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk auth $SNYK_TOKEN

    - name: Snyk Code Test
      run: snyk code test || true

    - name: Snyk Open Source Dependency Test
      run: snyk test || true

    - name: Snyk IaC Test (Terraform / CloudFormation / Kubernetes)
      run: snyk iac test || true

    - name: Snyk Container Test
      run: snyk container test <image-name> || true
  
  ########################################
  # Add a job for snyk scan of your code #
  ########################################

  ########################################
  # job name: snyk-checks
  # Enable:
  # - snyk code test
  # - snyk test
  # - snyk iac test
  # - snyk container test <image-name>
  # Also, enable:
  # outputs:
  #   status: ${{ job.status }}
  # for use in the summary
  ########################################

  #################################################
  # Finally, update summary for snyk-check        #
  # Update needs statement to include snyk-checks #
  #################################################
  summary:
    needs: [terraform-checks] # add snyk-checks 
    runs-on: ubuntu-latest
    steps:
      - name: Adding markdown
        run: |
          TF_STATUS=${{ needs.terraform-checks.outputs.status }}
          # SNYK_STATUS=${{ needs.snyk-checks.outputs.status }}

          echo '## ðŸš€ Preparing Build Summary ðŸš€' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY

          echo "| Job Name        | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| tf-check       | $TF_STATUS |" >> $GITHUB_STEP_SUMMARY
          # echo " snyk-check     | $SNYK_STATUS |" >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY

          echo '## Job ran by: ${{ github.actor }}' >> $GITHUB_STEP_SUMMARY

  summary: 
    needs: [snyk-checks] # add snyk-checks 
    runs-on: ubuntu-latest
    name: Snyk Summary Report
    needs: [terraform-validate, checkov, tflint, snyk-checks]
    steps:
      - name: Print Job Results
        run: |
          echo "Terraform Validation: ${{ needs.terraform-validate.result }}"
          echo "Checkov Scan: ${{ needs.checkov.result }}"
          echo "tflint Scan: ${{ needs.tflint.result }}"
          echo "Snyk Scan: ${{ needs.snyk-checks.result }}"
